### PR TITLE
Add package swift file & fix compile error

### PR DESCRIPTION
**Pull request by philipdolenko**

### CODE REVIEW

**Review by fawkeswei — CHANGES_REQUESTED** [review]
Mixed usage of Koala & koala

**Comment by philipdolenko** [comment]
I agree that it would be better to just have "Koala"

But since "koala" is actual repo name if dev would use "git clone" to get code to work locally there would be "koala" folder and for drag and drop folder name should be the same as package.

Maybe we could change repo name?

**Comment by gabrielPeart** [comment]
Can decide what to change, but I agree that is important to have consistency.

**Comment by fawkeswei** [comment]
> I agree that it would be better to just have "Koala"
> 
> But since "koala" is actual repo name if dev would use "git clone" to get code to work locally there would be "koala" folder and for drag and drop folder name should be the same as package.
> 
> Maybe we could change repo name?

Changed repo name to `Koala`

**Comment by philipdolenko** [comment]
Thanks @fawkeswei , I updated package.swift

**Review by gabrielPeart — APPROVED** [review]

**Review by fawkeswei — APPROVED** [review]

**Pull request merged**
